# Use a imagem oficial e leve do Nginx
FROM nginx:stable-alpine

# Remova a configuração padrão
RUN rm /etc/nginx/conf.d/default.conf

# Copie o seu arquivo de configuração personalizado
COPY default.conf /etc/nginx/conf.d/default.conf